// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GroupUsecase is an autogenerated mock type for the GroupUsecase type
type GroupUsecase struct {
	mock.Mock
}

type mockConstructorTestingTNewGroupUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewGroupUsecase creates a new instance of GroupUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGroupUsecase(t mockConstructorTestingTNewGroupUsecase) *GroupUsecase {
	mock := &GroupUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
