// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GroupData is an autogenerated mock type for the GroupData type
type GroupData struct {
	mock.Mock
}

type mockConstructorTestingTNewGroupData interface {
	mock.TestingT
	Cleanup(func())
}

// NewGroupData creates a new instance of GroupData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGroupData(t mockConstructorTestingTNewGroupData) *GroupData {
	mock := &GroupData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
